---

- name: Copy K3s service file
  template:
    src: "k3s.service.j2"
    dest: "{{ systemd_dir }}/k3s-agent.service"
    owner: root
    group: root
    mode: 0755

- name: Enable and check K3s service
  systemd:
    name: k3s-agent
    daemon_reload: yes
    state: restarted
    enabled: yes

- name: Reload systemd daemon to ensure latest service config
  systemd:
    daemon_reload: yes

- name: Enable and start the k3s agent service
  service:
    name: k3s-agent
    enabled: yes
    state: started

- name: Reboot pi
  reboot:

