---
- name: Ensure NFS utilities are installed.
  apt: 
    name: "{{ packages }}"
    state: installed
    update_cache: yes
  vars:  
    packages:
      - nfs-kernel-server

- name: copy /etc/exports
  template: 
    src: exports.j2
    dest: /etc/exports
    owner: root 
    group: root

- name: Restart the exports file.
  command: 'exportfs -ra'

- name: restart nfs server
  service: 
    name: nfs-kernel-server
    state: restarted

- name: Ensure nfs server is running
  service: 
    name: nfs-kernel-server
    state: started