---


- name: add line to /etc/exports
  lineinfile: 
    path: /etc/exports
    line: "{{nfs_server_dir}}\t192.168.0.1/24(rw,sync,no_subtree_check,insecure,no_root_squash)"
    insertafter: EOF
    state: present

- name: Restart the exports file.
  command: 'exportfs -ra'

- name: restart nfs server
  service: 
    name: nfs-kernel-server
    state: restarted

- name: Ensure nfs server is running
  service: 
    name: nfs-kernel-server
    state: started