---
- name: Ensure US locale exists
  locale_gen:
    name: en_US.UTF-8
    state: present
  async: 6400
  poll: 5
  
- name: Update apt cache and upgrade
  apt:
    update_cache: yes
    upgrade: yes
  async: 6400
  poll: 5

- name: Ensure NFS utilities are installed.
  apt: 
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - nfs-common
      - rpcbind
      - exfat-fuse
      - ntfs-3g
  async: 6400
  poll: 5

- name: Remove useless packages from the cache
  apt:
    autoclean: yes
    autoremove: yes
  async: 6400
  poll: 5
  