---
- name: write test to nfs server
  command: time dd if=/dev/zero of="{"{ client_mount_path }}"/testfile bs=16k count=16384

- name: read test to nfs server
  command: time dd if="{{ client_mount_path }}"/testfile of=/dev/null bs=16k

- name: remove testfile
  file:
    name: testfile
    exists: absent