---
- name: Add sudo k3s kubectl alias for pi user
  lineinfile:
    path="/home/pi/.bashrc"
    line="alias kubectl='sudo k3s kubectl'"
    state=present
    insertafter=EOF
    create=True

- name: Install the new path="/home/pi/.bashrc
  shell: source /home/pi/.bashrc
  args:
    executable: /bin/bash
    warn: False

# - name: Install build-essential
#   apt:
#     name: "build-essential" 
#     state: present

# - name: Install build lib packages
#   apt:
#     name: "tk-dev,libncurses5-dev,libncursesw5-dev,libreadline6-dev,libdb5.3-dev,libgdbm-dev,libsqlite3-dev,libssl-dev,libbz2-dev,libexpat1-dev,liblzma-dev,zlib1g-dev,libffi-dev,uuid-dev,vim,git,screen"
#     state: present

# - name: Install python packs and setuptools
#   apt:
#     name: "python-setuptools,python-pip,python3-dev,python3-pip,python3-setuptools"
#     state: present

# - name: install k8s pip deps
#   pip:
#     executable: pip3
#     name:
#       - openshift > 0.6
#       - PyYAML > 3.11
#     state: present

# - name: Overlook YAML warning
#   shell: export PYTHONWARNINGS=ignore::yaml.YAMLLoadWarning
#   args:
#     warn: False

